name: CI/CD

on: [push, pull_request]

jobs:
  test:
    name: Run Tests 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
